version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "5005:5005"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    build: 
      context: .
      dockerfile: Dockerfile-server
    command: celery -A server.tasks.celery worker --loglevel=info
    depends_on:
      - redis
    restart: unless-stopped
